load Vid2Seq model
Traceback (most recent call last):
  File "demo_vid2seq.py", line 55, in <module>
    tokenizer = _get_tokenizer(args.model_name, args.num_bins)
  File "/ifs/CS/replicated/home/tzhu38/VidChapters/model/vid2seq.py", line 12, in _get_tokenizer
    tokenizer = T5Tokenizer.from_pretrained(tokenizer_path, local_files_only=True)
  File "/home/tzhu38/miniconda3/envs/vid2seq/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 1784, in from_pretrained
    _commit_hash=commit_hash,
  File "/home/tzhu38/miniconda3/envs/vid2seq/lib/python3.7/site-packages/transformers/utils/hub.py", line 420, in cached_file
    local_files_only=local_files_only,
  File "/home/tzhu38/miniconda3/envs/vid2seq/lib/python3.7/site-packages/huggingface_hub/utils/_validators.py", line 110, in _inner_fn
    validate_repo_id(arg_value)
  File "/home/tzhu38/miniconda3/envs/vid2seq/lib/python3.7/site-packages/huggingface_hub/utils/_validators.py", line 159, in validate_repo_id
    "Repo id must be in the form 'repo_name' or 'namespace/repo_name':"
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': './cache/t5-base'. Use `repo_type` argument if needed.
